### ISSUE TITLE
Inconsistent issue when the protection mode is ON

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/OperationKeyManagement#284]
In the test environment , when the protection mode is ON in OKM , after a while , OKM application is stopping. 
This is an inconsistent issue.

Logs :
```diff
Successfully updated operation key for application ApplicationLayerTopology version 2.0.1 operation alt-2-0-1-op-s-bm-001
Successfully updated operation key for application ApplicationLayerTopology version 2.0.1 operation alt-2-0-1-op-s-bm-003
Successfully updated operation key for application ApplicationLayerTopology version 2.0.1 operation alt-2-0-1-op-s-is-021
Successfully updated operation key for application ApplicationLayerTopology version 2.0.1 operation alt-2-0-1-op-s-bm-000
Successfully updated operation key for application ApplicationLayerTopology version 2.0.1 operation alt-2-0-1-op-s-is-019
Successfully updated operation key for application ApplicationLayerTopology version 2.0.1 operation alt-2-0-1-op-s-is-018
Successfully updated operation key for application ApplicationLayerTopology version 2.0.1 operation alt-2-0-1-op-s-is-020
Successfully updated operation key for application ApplicationLayerTopology version 2.0.1 operation alt-2-0-1-op-s-bm-010
POST /v1/update-operation-key 204 14.196 ms - -
Successfully updated operation key for application OperationKeyManagement version 2.0.1 operation okm-2-0-1-op-c-is-alt-1-0-0-000
POST /v1/update-operation-key 204 10.063 ms - -
Successfully updated operation key for application OperationKeyManagement version 2.0.1 operation okm-2-0-1-op-s-bm-010
-node:internal/errors:478
-ErrorCaptureStackTrace(err);
-^
-Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
- at new NodeError (node:internal/errors:387:5)
- at ServerResponse.setHeader (node:_http_outgoing:644:11)
- at ServerResponse.header (/home/node/node_modules/express/lib/response.js:794:10)
- at ServerResponse.header (/home/node/node_modules/express/lib/response.js:797:12)
- at Object.exports.buildResponse (/home/node/node_modules/onf-core-model-ap/applicationPattern/rest/server/ResponseBuilder.js:26:14)
-at /home/node/controllers/BasicServices.js:317:42
-at async SwaggerRouter.updateOperationKey (/home/node/controllers/BasicServices.js:309:3) {
-code: 'ERR_HTTP_HEADERS_SENT'
-}
```

**Comment by DanaSunal** [comment]
It seems it is consistent and appears whenever the condition `if (uuidToBeUpdated == operationServerOfUpdateOperationKeyInOKM)` is true. When it is true, the function is trying to send two responses (one for client and one for server), which is not possible. 
[StackOverflow problem description](https://stackoverflow.com/questions/7042340/error-cant-set-headers-after-they-are-sent-to-the-client).

This was introduced here: #256 unfortunately there are no details to the issue.

**Comment by PrathibaJee** [comment]
The code changes were included as a temporary fix for the issue https://github.com/openBackhaul/OperationKeyManagement/issues/258. Thanks for resolving the inconsistent problem.
